version: '3'
services:
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./src:/opt/html
        ports:
            - 80:80
        logging:
            driver: json-file